# Generated by Django 5.0.1 on 2024-01-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_achievement_user_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
    ]
